### ISSUE TITLE
programming.dev instance does not work

### ISSUE THREAD

**Issue by aaronkurz** [diamondburned/slemmy#14]
I have problems connecting to the programming.dev instance:
![Screenshot 2023-06-29 at 08 55 25](https://github.com/diamondburned/slemmy/assets/62746723/da644362-f1e6-4128-b5b4-45facf840182)

It's weird, since the instance works fine with the [Mlem](https://github.com/mormaer/Mlem) app!

**Comment by diamondburned** [comment]
programming.dev uses Lemmy v0.18. Unfortunately, Slemmy doesn't work with Lemmy v0.18+ instances at the moment because of the removal of the WS API and the lack of proper CORS support.

(I believe hovering over the red X will tell you the error.)

Relevant issues:

- https://github.com/LemmyNet/lemmy/issues/3109
- https://github.com/LemmyNet/lemmy/pull/3301

I've also added a section into the README calling attention to these issues. Please upvote them to show support!

**Comment by diamondburned** [comment]
Once programming.dev updates to Lemmy v0.18.1, Slemmy should work fine with it.

**Comment by diamondburned** [comment]
It's been almost a year. This instance works fine now.

![image](https://github.com/diamondburned/slemmy/assets/8463786/e30210da-0dde-4cca-8e26-76f4cfd82a8c)
